name: validator
description: Sirius validator application

publish_to: "none"

version: 0.0.25+25

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.15.0
  get_storage: ^1.3.2
  steel_crypt: ^2.2.2+1
  crypton: ^1.1.1
  crypto: ^2.1.5
  qr_flutter: ^3.2.0
  barcode_scan_fix: ^1.0.2
  local_auth: ^0.6.3+3
  share: ^0.6.5+2
  device_info: '>=0.4.2+9 <2.0.0'
  grpc: ^2.3.0
  protobuf: ^1.0.1
  clipboard: ^0.1.2+8
  flutter_spinkit: ^4.1.2+1
  intl: ^0.15.8
  logger_flutter: ^0.7.1
  equatable: ^1.2.5
  argon_buttons_flutter: ^1.0.6
  flutter_money_formatter: ^0.8.3
  package_info: ^0.4.3
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.0+2
  protoc_plugin: ^19.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
